seed: 42
dtype: bfloat16

parallelism:
  dp: 1
  pp: 1
  tp: 1

model:
  vlm_model_name: /root/autodl-tmp/smolvla-minimal/cache/huggingface/hub/models--HuggingFaceTB--SmolVLM2-500M-Video-Instruct/snapshots/7b375e1b73b11138ff12fe22c8f2822d8fe03467
  load_vlm_weights: false
  train_expert_only: true
  freeze_vision_encoder: true
  train_state_proj: true
  attention_mode: cross_attn
  num_vlm_layers: 2
  num_expert_layers: 2
  self_attn_every_n_layers: 2
  expert_width_multiplier: 0.75
  max_state_dim: 32
  max_action_dim: 32
  chunk_size: 8
  tokenizer_max_length: 48
  image_key: observation.images.main
  image_shape: [3, 512, 512]
  device: cuda
  compile_model: false

tokens:
  train_steps: 2
  micro_batch_size: 1
  batch_accumulation_per_replica: 1

optimizer:
  lr: 0.0001
  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 1.0e-10
  clip_grad: 10.0
  fused: true

dummy_data:
  language_vocab_size: 49152

